name: showcase_flutter
description: 'A showcase of Flutter components using the Candi color palette.'
publish_to: 'none'
version: 0.0.27

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  candi_colors:
    path: ../flutter
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
